module.exports = {
  name: 'invite',
  description: 'Invite a user to the group (Creators/Admins Only)',
  async execute(bot, msg, args) {
    if (msg.chat.type !== 'group' && msg.chat.type !== 'supergroup') {
      return bot.sendMessage(msg.chat.id, '❌ This command can only be used in groups.');
    }

    if (args.length !== 1 || !args[0].startsWith('@')) {
      return bot.sendMessage(msg.chat.id, '❌ Usage: /invite @username');
    }

    try {
      const senderChatMember = await bot.getChatMember(msg.chat.id, msg.from.id);

      if (senderChatMember.status !== 'creator' && senderChatMember.status !== 'administrator') {
        return bot.sendMessage(msg.chat.id, `
🚫 <b>Permission Denied</b>

Only group creators and administrators can invite users.
Your current status: ${senderChatMember.status}
        `, { parse_mode: 'HTML' });
      }

      if (senderChatMember.status === 'administrator' && !senderChatMember.can_invite_users) {
        return bot.sendMessage(msg.chat.id, '🚫 You do not have permission to invite users.');
      }

      const username = args[0].replace('@', '');

      try {
        const inviteLink = await bot.exportChatInviteLink(msg.chat.id);

        bot.sendMessage(msg.chat.id, `
✅ <b>Invite Link Generated!</b>

Invite @${username} using this link:
${inviteLink}

Invite generated by: @${msg.from.username || 'Unknown'}
        `, { 
          parse_mode: 'HTML',
          disable_web_page_preview: true
        });

      } catch (inviteError) {
        console.error('Invite Link Error:', inviteError);

        const errorMessage = inviteError.response?.body?.description || 'Unknown error';

        if (errorMessage.includes('not enough rights')) {
          return bot.sendMessage(msg.chat.id, '🚫 Bot lacks permission to generate invite link.');
        }

        bot.sendMessage(msg.chat.id, '❌ Failed to generate invite link. Please try again later.');
      }

    } catch (permissionError) {
      console.error('Permission Check Error:', permissionError);
      bot.sendMessage(msg.chat.id, '❌ Unable to verify your admin status.');
    }
  }
};